CREATE TABLE TB_PESSOA (
	CODIGO INTEGER PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
	TIPO_PESSOA CHAR(1) NOT NULL,
	EMAIL VARCHAR(150) NOT NULL,
	SITE VARCHAR(200),
	CLIENTE CHAR(1) NOT NULL,
	FORNECEDOR CHAR(1) NOT NULL,
	COLABORADOR CHAR(1) NOT NULL,
	TRANSPORTADORA CHAR(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;